POST http://localhost:3000/user/signup
Content-Type: application/json

{
   "name": "Norman Osbourne", 
   "email": "osbourne@oscorap.com" ,
   "password": "ihatepeter",
   "role": "NORMAL"
}

###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "name": "Norman Osbourne",
    "password": "ihatepeter"
}

###
POST http://localhost:3000/band/create
Content-Type: application/json

{
    "name": "Foo Fighters",
    "music_genre": "rock",
    "responsible": "Dave Grohl"

}